package com.xjh.search.db.search;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xjh.search.db.SearchName;

import com.xjh.search.db.search.SearchNameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchNameDaoConfig;

    private final SearchNameDao searchNameDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchNameDaoConfig = daoConfigMap.get(SearchNameDao.class).clone();
        searchNameDaoConfig.initIdentityScope(type);

        searchNameDao = new SearchNameDao(searchNameDaoConfig, this);

        registerDao(SearchName.class, searchNameDao);
    }
    
    public void clear() {
        searchNameDaoConfig.clearIdentityScope();
    }

    public SearchNameDao getSearchNameDao() {
        return searchNameDao;
    }

}
